Repository RasaHQ/rasa-demo, pull requests merged in 2020-10, with the labels that each got.

#583 Add need_help_broad & utter_ask_more_details
  data/nlu/general.yml
  data/rules/rules.yml
  data/stories/stories.yml
  domain.yml
Labels: demo, enhancement

#590 Make pronouns general where they have no reason to be specific.
  actions/actions.py
  data/nlu/responses/responses.yml
Labels: demo, enhancement, status:ready-to-merge

#566 Converting Rasa-Demo to 2.0 Format
  Dockerfile
  actions/actions.py
  actions/requirements-actions.txt
  config.yml
  data/core/canthelp.md
  data/core/chitchat.md
  data/core/closetheloop.md
  data/core/faqs.md
  data/core/feedback.md
  data/core/handoff.md
  data/core/oos.md
  data/core/step1_get_started.md
  data/core/step2_rasa_init.md
  data/core/step3_rasa_x.md
  data/core/step4_community.md
  data/core/stories.md
  data/nlu/chitchat.md
  data/nlu/chitchat.yml
  data/nlu/faq.md
  data/nlu/faq.yml
  data/nlu/general.md
  data/nlu/general.yml
  data/nlu/lookups/location.txt
  data/nlu/lookups/location.yml
  data/nlu/lookups/products.txt
  data/nlu/lookups/products.yml
  data/nlu/nlu.md
  data/nlu/nlu.yml
  data/nlu/out_of_scope.md
  data/nlu/out_of_scope.yml
  data/nlu/responses/responses.md
  data/nlu/responses/responses.yml
  data/rules/fallback.yml
  data/rules/feedback.yml
  data/rules/forms.yml
  data/rules/rules.yml
  data/stories/canthelp.yml
  data/stories/chitchat.yml
  data/stories/closetheloop.yml
  data/stories/faqs.yml
  data/stories/handoff.yml
  data/stories/oos.yml
  data/stories/step1_get_started.yml
  data/stories/step2_rasa_init.yml
  data/stories/step3_rasa_x.yml
  data/stories/step4_community.yml
  data/stories/stories.yml
  domain.yml
  requirements.txt
  setup.py
  test/test_conversations.md
  test/test_nlu.md
  test/test_stories.md
  tests/test_conversations.yml
  tests/test_nlu.yml
Labels: nlu_testing_required
