Repository RasaHQ/rasa-demo, pull requests merged in 2021-03, with the labels that each got.

#617 Update NLU test data
  tests/test_nlu.yml
Labels: demo, status:ready-to-merge

#613 Add NLU test examples for intents currently not covered
  data/nlu/general.yml
  data/nlu/nlu.yml
Labels: demo, status:ready-to-merge

#616 Add NLU training examples for chitchat/ask_whoisit
  data/nlu/chitchat.yml
Labels: demo, status:ready-to-merge

#575 Fix markdown syntax in domain.yml responses
  domain.yml
Labels: status:ready-to-merge

#620 Story fragments -> rules
  data/rules/rules.yml
  data/stories/closetheloop.yml
  data/stories/faqs.yml
  data/stories/stories.yml
Labels: demo
